name:                fsmark
version:             0.3.0.0
github:              "0x00002a/file-shelf"
license:             GPL-3
author:              "Natasha England-Elbro"
maintainer:          "natenglandelbro@gmail.com"
copyright:           "2020 Natasha England-Elbro"

extra-source-files:
- README.md
- LICENSE

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0x00002a/file-shelf#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- sqlite-simple >= 0.4.18
- text
- path
- directory
- filepath
- aeson
- bytestring
- mtl
- Unique
library:
  source-dirs: src

executables:
  fsm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fsmark

tests:
  fsm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fsmark
    - HUnit
